version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
    labels:
      - 'dependencies'
      - 'github_actions'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
    labels:
      - 'dependencies'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/examples/async-flush'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
    labels:
      - 'dependencies'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/examples/custom-axios'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
    labels:
      - 'dependencies'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/examples/sample-app'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
    labels:
      - 'dependencies'
    open-pull-requests-limit: 0
