version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "daily"
    target-branch: "develop"
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily"
    groups:
      npm-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    target-branch: "develop"
