version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      # every wednesday at 00:01 UTC
      cronjob: "1 0 * * 3"
      timezone: "UTC"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
    groups:
      github-actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    cooldown:
      default-days: 5
    directory: "/"
    schedule:
      interval: "cron"
      # every wednesday at 00:01 UTC
      cronjob: "1 0 * * 3"
      timezone: "UTC"
    target-branch: "develop"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    groups:
      npm-dev-deps:
        patterns:
          - "*"
        dependency-type: "development"

      npm-prod-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        dependency-type: "production"

      npm-prod-major-deps:
        patterns:
          - "*"
        update-types:
          - "major"
        dependency-type: "production"
